version: "3.7"

services:
  web:
    depends_on:
      - db
    image: tomcat
    volumes:
      - ./target/rent-a-car-2.war:/usr/local/tomcat/webapps/rent-a-car-2.war
    ports:
      - '8082:8080'
    environment:
      POSTGRES_DB: car
      POSTGRES_USER: pasha
      POSTGRES_PASSWORD: admin

  db:
    image: postgres:12.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: car
      POSTGRES_USER: pasha
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data

    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    # networks:
    #   - postgres

  pgadmin:
    # container_name: pgadmin_container
    image: dpage/pgadmin4:4.18
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: fghjkl11@gmail.com  #${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: admin #${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 80

    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

    # networks:
    #   - postgres

volumes:
  db-data:
  pgadmin-data:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16





  # version: '3'
  # services:
  #   mysql-docker:
  #     image: mysql/mysql-server:8.0
  #     volumes:
  #       - "./.data/db:/var/lib/mysql"
  #     environment:
  #       MYSQL_ROOT_HOST: "%"
  #       MYSQL_ROOT_USERNAME: pasha
  #       MYSQL_ROOT_PASSWORD: admin
  #       MYSQL_DATABASE: car
  #     ports:
  #       - "3306:3306"
