name: Java install openjdk-11-jdk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: sudo apt-get update
        run: sudo apt-get update

      - name: sudo apt-get install openjdk-11-jdk
        run: sudo apt-get install openjdk-11-jdk -y

      - name: mvn -B package --file pom.xml
        run: mvn -B package --file pom.xml

      - name: clean install test surefire-report:report
        run: mvn clean install test surefire-report:report

#      - name: bash_profile
#        run: source .bash_profile

      - name: Run maven script
        uses: guillonapa/action-maven-cli/jdk11@master
        with:
          lifecycle: 'clean package test'